export const DATA_FETCH_START = Symbol('DATA_FETCH_START');
export const DATA_FETCH_SUCCESS = Symbol('DATA_FETCH_SUCCESS');
export const DATA_FETCH_FAILURE = Symbol('DATA_FETCH_FAILURE');

export const APPOINTMENTS_FETCH_START = Symbol('APPOINTMENTS_FETCH_START');
export const APPOINTMENTS_FETCH_SUCCESS = Symbol('APPOINTMENTS_FETCH_SUCCESS');
export const APPOINTMENTS_FETCH_FAILURE = Symbol('APPOINTMENTS_FETCH_FAILURE');
