export const DATA_FETCH_START = Symbol('DATA_FETCH_START');
export const DATA_FETCH_SUCCESS = Symbol('DATA_FETCH_SUCCESS');
export const DATA_FETCH_FAILURE = Symbol('DATA_FETCH_FAILURE');

export const APPOINTMENTS_FETCH_START = Symbol('APPOINTMENTS_FETCH_START');
export const APPOINTMENTS_FETCH_SUCCESS = Symbol('APPOINTMENTS_FETCH_SUCCESS');
export const APPOINTMENTS_FETCH_FAILURE = Symbol('APPOINTMENTS_FETCH_FAILURE');

export const SECRETARYAPPOINTMENTS_FETCH_START = Symbol('SECRETARYAPPOINTMENTS_FETCH_START');
export const SECRETARYAPPOINTMENTS_FETCH_SUCCESS = Symbol('SECRETARYAPPOINTMENTS_FETCH_SUCCESS');
export const SECRETARYAPPOINTMENTS_FETCH_FAILURE = Symbol('SECRETARYAPPOINTMENTS_FETCH_FAILURE');
export const CHANGE_STATUS = Symbol('CHANGE_STATUS');

export const RESERVE_TIME = Symbol('RESERVE_TIME');

export const RESERVE_DATA_PATIENT = Symbol('RESERVE_DATA_PATIENT');
