export const DATA_FETCH_START = Symbol('DATA_FETCH_START');
export const DATA_FETCH_SUCCESS = Symbol('DATA_FETCH_SUCCESS');
export const DATA_FETCH_FAILURE = Symbol('DATA_FETCH_FAILURE');

export const CALENDER_FETCH_START = Symbol('CALENDER_FETCH_START');
export const CALENDER_FETCH_SUCCESS = Symbol('CALENDER_FETCH_SUCCESS');
export const CALENDER_FETCH_FAILURE = Symbol('CALENDER_FETCH_FAILURE');

export const RESERVE_TIME = Symbol('RESERVE_TIME');
export const RESERVE_ERROR = Symbol(' RESERVE_ERROR');

export const RESERVE_DATA_PATIENT = Symbol('RESERVE_DATA_PATIENT');
